# Version
version: "3.9"

# Containers
services:
  # Container names
  web:
    # Docker file
    build: .
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=admin${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      # mysql -> /var/lib/mysql
      # mongo -> /data/db

# All volumes
volumes:
  db-data:
    
