# Image:version
FROM python:3.10

# Create a folder in docker
RUN mkdir -p /home/app

# Work route
WORKDIR /home/app

# Copy requirements
COPY ./requirements.txt /home/app/requirements.txt

# Install requirements
RUN pip install --no-cache-dir --upgrade -r /home/app/requirements.txt

# Exposed a port
EXPOSE 8000

# Run command
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]